### PR TITLE
Update the main branch

### PR DESCRIPTION
**Pull request by winonafeminine**

### CODE REVIEW

**Comment by winonafeminine** [comment]
My latest update

**Comment by winonafeminine** [comment]
screenshot-20211127-084612

**Comment by NareeyaChenu** [comment]
Update Last Contact Page
image

**Comment by Has12Wan34** [comment]
ภาพหน้าจอ (2)

**Comment by suha3001** [comment]
7fa0fd8a-dec3-44c9-b8c7-46d1b0ff165c

**Pull request merged**
